"""Seed the database with LGBTQ+ places across LA, SF, NYC, and Miami."""

import os
import time
from datetime import datetime, timezone

from dotenv import load_dotenv
from mongoengine import connect

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI", "mongodb://mongo:27017/qwermapdb")
MONGO_DB = os.getenv("MONGO_DB", "qwermapdb")

# ── Los Angeles ───────────────────────────────────────────────────────────────

LA_PLACES = [
    {
        "transaction_id": "5vwJm7W2kP9xN4rQsF8dLbY3cMaZhE6tV1uGjH7nKoS",
        "name": "The Abbey Food & Bar",
        "location": {"type": "Point", "coordinates": [-118.3802, 34.0878]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 92,
        "upvote_count": 247,
        "description": "Iconic LGBTQ+ bar and restaurant in West Hollywood, known as one of the best gay bars in the world. Features multiple rooms, outdoor patios, and weekend brunches.",
        "address": "692 N Robertson Blvd, West Hollywood, CA 90069",
        "photos": ["https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800"],
        "movements": ["pride", "gay_liberation"],
        "community_tags": ["gay", "lesbian", "queer", "drag"],
        "site_types": ["bar"],
        "year_opened": 1991,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "The Abbey opens on Robertson Blvd", "date": "1991", "description": "Originally a small coffeehouse, it grew into one of the most famous LGBTQ+ venues in the world."},
        ],
        "related_figures": [
            {"name": "David Cooley", "role": "Founder", "description": "Founded The Abbey and grew it into an internationally recognized LGBTQ+ venue."},
        ],
    },
    {
        "transaction_id": "3kR8mN5vXp2wQ7tYdB4jL6hFaC9sE1oUgZ0iM3nWxV",
        "name": "Black Cat Tavern",
        "location": {"type": "Point", "coordinates": [-118.2765, 34.0868]},
        "place_type": "historical",
        "category": "bar",
        "safety_score": 78,
        "upvote_count": 183,
        "description": "Site of one of the first LGBTQ+ civil rights demonstrations in the US on New Year's Eve 1967, predating Stonewall by over a year. Now a California Historical Landmark.",
        "era": "1960s",
        "address": "3909 W Sunset Blvd, Los Angeles, CA 90029",
        "movements": ["gay_liberation", "homophile_movement"],
        "community_tags": ["gay", "lesbian"],
        "site_types": ["bar", "protest_site"],
        "year_opened": 1966,
        "year_closed": 1967,
        "still_exists": "partial",
        "significance": "national",
        "events": [
            {"title": "New Year's Eve police raid", "date": "1966-12-31", "description": "Police raided the bar and arrested patrons for same-sex kissing on New Year's Eve."},
            {"title": "Protest demonstration", "date": "1967-02-11", "description": "Over 200 people marched in one of the first LGBTQ+ civil rights demonstrations in US history."},
            {"title": "California Historical Landmark designation", "date": "2008", "description": "Designated California Historical Landmark No. 1048."},
        ],
        "related_figures": [
            {"name": "Lee Glaze", "role": "Organizer", "description": "Bar owner who helped organize the protest response to the police raid."},
        ],
    },
    {
        "transaction_id": "7pL4nK2mX8wR5tYsD3jF6hBaC1vE9oUgZ0qM7nWxQ",
        "name": "Akbar",
        "location": {"type": "Point", "coordinates": [-118.269, 34.087]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 88,
        "upvote_count": 156,
        "description": "Beloved Silver Lake dive bar known for its inclusive atmosphere, strong drinks, and eclectic jukebox. A neighborhood staple since 1998.",
        "address": "4356 W Sunset Blvd, Los Angeles, CA 90029",
        "movements": ["pride"],
        "community_tags": ["gay", "queer", "lesbian", "bisexual"],
        "site_types": ["bar"],
        "year_opened": 1998,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "9qM5nK3pX7wR4tYsE2jF8hBaD1vC6oUgZ0rL7nWxS",
        "name": "ONE National Gay & Lesbian Archives",
        "location": {"type": "Point", "coordinates": [-118.2837, 34.0187]},
        "place_type": "current",
        "category": "library",
        "safety_score": 95,
        "upvote_count": 312,
        "description": "The largest repository of LGBTQ+ materials in the world, housed at USC Libraries. Contains over two million archival items documenting LGBTQ+ history.",
        "address": "909 W Adams Blvd, Los Angeles, CA 90007",
        "movements": ["homophile_movement", "gay_liberation", "aids_activism", "marriage_equality"],
        "community_tags": ["gay", "lesbian", "bisexual", "trans", "queer"],
        "site_types": ["archive", "library"],
        "year_opened": 1952,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "ONE, Inc. founded", "date": "1952", "description": "Started as ONE Magazine, the first pro-gay publication in the US, during the homophile movement era."},
            {"title": "ONE, Inc. v. Olesen Supreme Court victory", "date": "1958-01-13", "description": "The US Supreme Court ruled in favor of ONE Magazine's right to distribute, a landmark First Amendment case."},
            {"title": "Archives move to USC Libraries", "date": "2010", "description": "Collection moved to USC, ensuring long-term preservation and academic access."},
        ],
        "related_figures": [
            {"name": "Jim Kepner", "role": "Archivist", "description": "Pioneering collector whose personal archive became the foundation of the ONE Archives."},
            {"name": "Dorr Legg", "role": "Co-founder", "description": "Co-founded ONE, Inc. and guided the organization through its landmark Supreme Court case."},
        ],
    },
    {
        "transaction_id": "2rN6oL4qY8xS5uZtF3kG9iCbE1wD7pVhA0sM8nXyT",
        "name": "Los Angeles LGBT Center",
        "location": {"type": "Point", "coordinates": [-118.3442, 34.0937]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 97,
        "upvote_count": 489,
        "description": "The world's largest provider of programs and services for LGBTQ+ people. Offers health services, housing, legal aid, arts & culture, and more.",
        "address": "1118 N McCadden Pl, Los Angeles, CA 90038",
        "photos": ["https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800"],
        "movements": ["gay_liberation", "aids_activism", "trans_rights", "marriage_equality"],
        "community_tags": ["gay", "lesbian", "bisexual", "trans", "queer", "nonbinary", "youth", "elders"],
        "site_types": ["community_center", "health_clinic", "shelter"],
        "year_opened": 1969,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "Founded as Gay Community Services Center", "date": "1969", "description": "One of the first LGBTQ+ community centers in the world, founded by Morris Kight."},
            {"title": "Anita May Rosenstein Campus opens", "date": "2019", "description": "State-of-the-art campus providing senior housing, youth housing, and expanded services."},
        ],
        "related_figures": [
            {"name": "Morris Kight", "role": "Founder", "description": "Pioneering activist who founded the center and was central to LA's gay liberation movement."},
            {"name": "Lorri L. Jean", "role": "CEO", "description": "Led the center for over two decades, overseeing massive growth in programs and services."},
        ],
    },
    {
        "transaction_id": "4sO7pM5rZ9yT6vAuG4lH0jDcF2xE8qWhB1tN9oYzU",
        "name": "Circus of Books",
        "location": {"type": "Point", "coordinates": [-118.2679, 34.091]},
        "place_type": "historical",
        "category": "bookstore",
        "safety_score": 72,
        "upvote_count": 134,
        "description": "Former adult bookstore and cultural landmark in Silver Lake that served as an important community gathering space. Subject of a Netflix documentary.",
        "era": "1980s-2019",
        "address": "4001 W Sunset Blvd, Los Angeles, CA 90029",
        "movements": ["aids_activism", "gay_liberation"],
        "community_tags": ["gay"],
        "site_types": ["bookstore"],
        "year_opened": 1982,
        "year_closed": 2019,
        "still_exists": "no",
        "significance": "regional",
        "events": [
            {"title": "Netflix documentary released", "date": "2020-04-22", "description": "'Circus of Books' documentary premiered, telling the story of the straight couple who ran one of LA's most prominent gay bookstores."},
        ],
        "related_figures": [
            {"name": "Karen Mason", "role": "Owner", "description": "Co-owned Circus of Books with her husband Barry, becoming one of the largest distributors of gay pornography in the US."},
            {"name": "Barry Mason", "role": "Owner", "description": "Co-owned the store for nearly four decades with his wife Karen."},
        ],
    },
    {
        "transaction_id": "6tP8qN6sA0zU7wBvH5mI1kEdG3yF9rXiC2uO0pZaV",
        "name": "Cuties Coffee",
        "location": {"type": "Point", "coordinates": [-118.2551, 34.0772]},
        "place_type": "current",
        "category": "cafe",
        "safety_score": 90,
        "upvote_count": 198,
        "description": "LA's first LGBTQ+-focused coffee shop in East Hollywood. Community-centered space hosting events, art shows, and open mic nights.",
        "address": "1034 N Virgil Ave, Los Angeles, CA 90029",
        "movements": ["pride"],
        "community_tags": ["queer", "nonbinary", "trans", "bipoc_queer"],
        "site_types": ["cafe", "community_center"],
        "year_opened": 2017,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "8uQ9rO7tB1aV8xCwI6nJ2lFeH4zG0sYjD3vP1qAbW",
        "name": "Flaming Saddles Saloon",
        "location": {"type": "Point", "coordinates": [-118.3764, 34.0904]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 85,
        "upvote_count": 142,
        "description": "Country-western gay bar in WeHo where the bartenders dance on the bar. Known for its fun, high-energy atmosphere and line dancing nights.",
        "address": "8811 Santa Monica Blvd, West Hollywood, CA 90069",
        "movements": ["pride"],
        "community_tags": ["gay"],
        "site_types": ["bar", "nightclub"],
        "year_opened": 2014,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "0vR0sP8uC2bW9yDxJ7oK3mGfI5aH1tZkE4wQ2rBcX",
        "name": "Plummer Park",
        "location": {"type": "Point", "coordinates": [-118.3649, 34.0849]},
        "place_type": "current",
        "category": "park",
        "safety_score": 80,
        "upvote_count": 98,
        "description": "Historic West Hollywood park with a long history as a gathering place for the LGBTQ+ community. Home to community events and the WeHo Pride festival.",
        "address": "7377 Santa Monica Blvd, West Hollywood, CA 90046",
        "movements": ["pride", "gay_liberation"],
        "community_tags": ["gay", "lesbian", "queer"],
        "site_types": ["park"],
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "1wS1tQ9vD3cX0zEyK8pL4nHgJ6bI2uAlF5xR3sCdY",
        "name": "MOCA Pacific Design Center",
        "location": {"type": "Point", "coordinates": [-118.379, 34.0862]},
        "place_type": "current",
        "category": "art_space",
        "safety_score": 82,
        "upvote_count": 107,
        "description": "Contemporary art museum inside the Pacific Design Center in WeHo. Frequently hosts exhibitions exploring LGBTQ+ themes and queer art.",
        "address": "8687 Melrose Ave, West Hollywood, CA 90069",
        "movements": ["pride"],
        "community_tags": ["queer"],
        "site_types": ["art_space"],
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "2xT2uR0wE4dY1aFzL9qM5oIhK7cJ3vBmG6yS4tDeZ",
        "name": "Precinct DTLA",
        "location": {"type": "Point", "coordinates": [-118.233, 34.046]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 83,
        "upvote_count": 89,
        "description": "Downtown LA gay bar with an industrial-chic vibe. Features pool tables, strong cocktails, and a welcoming atmosphere for the Arts District crowd.",
        "address": "357 S Broadway, Los Angeles, CA 90013",
        "movements": ["pride"],
        "community_tags": ["gay", "queer"],
        "site_types": ["bar"],
        "year_opened": 2015,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "3yU3vS1xF5eZ2bGaM0rN6pJiL8dK4wCnH7zT5uEfA",
        "name": "Cooper Do-nuts",
        "location": {"type": "Point", "coordinates": [-118.2467, 34.0445]},
        "place_type": "historical",
        "category": "cafe",
        "safety_score": 65,
        "upvote_count": 167,
        "description": "Site of the 1959 Cooper Do-nuts Riot \u2014 one of the first LGBTQ+ uprisings in US history, a decade before Stonewall. Patrons resisted police harassment.",
        "era": "1950s-1960s",
        "address": "327 S Main St, Los Angeles, CA 90013",
        "movements": ["gay_liberation", "trans_rights"],
        "community_tags": ["trans", "gay", "drag", "bipoc_queer"],
        "site_types": ["cafe", "protest_site"],
        "year_opened": 1950,
        "year_closed": 1967,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "Cooper Do-nuts Riot", "date": "1959-05", "description": "Trans women, drag queens, and gay men fought back against police harassment, throwing doughnuts and coffee cups at officers in one of the earliest LGBTQ+ uprisings in the US."},
        ],
    },
    {
        "transaction_id": "4zV4wT2yG6fA3cHbN1sO7qKjM9eL5xDoI8aU6vFgB",
        "name": "A Different Light Bookstore",
        "location": {"type": "Point", "coordinates": [-118.3801, 34.0893]},
        "place_type": "historical",
        "category": "bookstore",
        "safety_score": 70,
        "upvote_count": 145,
        "description": "Legendary LGBTQ+ bookstore that operated on Santa Monica Blvd in WeHo. A vital community gathering space and hub for queer literature and culture.",
        "era": "1980s-2011",
        "address": "8853 Santa Monica Blvd, West Hollywood, CA 90069",
        "movements": ["gay_liberation", "aids_activism"],
        "community_tags": ["gay", "lesbian", "queer"],
        "site_types": ["bookstore"],
        "year_opened": 1979,
        "year_closed": 2011,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "West Hollywood location opens", "date": "1983", "description": "Became a cultural hub for the LGBTQ+ literary community and a vital gathering space during the AIDS crisis."},
            {"title": "Final closure", "date": "2011", "description": "The last A Different Light location closed, ending an era of LGBTQ+ independent bookselling."},
        ],
    },
    {
        "transaction_id": "5aW5xU3zH7gB4dIcO2tP8rLkN0fM6yEpJ9bV7wGhC",
        "name": "Mattachine Steps",
        "location": {"type": "Point", "coordinates": [-118.252, 34.0665]},
        "place_type": "historical",
        "category": "other",
        "safety_score": 60,
        "upvote_count": 88,
        "description": "Public staircase in Silver Lake named after the Mattachine Society, one of the earliest LGBTQ+ rights organizations in the US, founded nearby in 1950.",
        "era": "1950s",
        "address": "2355 Cove Ave, Los Angeles, CA 90039",
        "movements": ["homophile_movement", "gay_liberation"],
        "community_tags": ["gay"],
        "site_types": ["memorial"],
        "year_opened": 1950,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Mattachine Society founded", "date": "1950-11-11", "description": "Harry Hay and a small group founded the Mattachine Society in a Silver Lake home, launching the homophile movement."},
            {"title": "Steps officially named", "date": "2012", "description": "The public staircase was officially designated as the Mattachine Steps by the City of Los Angeles."},
        ],
        "related_figures": [
            {"name": "Harry Hay", "role": "Founder", "description": "Founded the Mattachine Society, considered the father of the American gay rights movement."},
        ],
    },
    {
        "transaction_id": "6bX6yV4aI8hC5eJdP3uQ9sLlO1gN7zFqK0cW8xHiD",
        "name": "Highways Performance Space",
        "location": {"type": "Point", "coordinates": [-118.4698, 34.0195]},
        "place_type": "current",
        "category": "art_space",
        "safety_score": 86,
        "upvote_count": 112,
        "description": "Legendary performance space in Santa Monica dedicated to diverse voices. Has been a crucial platform for LGBTQ+ artists and performers since 1989.",
        "address": "1651 18th St, Santa Monica, CA 90404",
        "movements": ["aids_activism", "pride"],
        "community_tags": ["queer", "bipoc_queer", "trans"],
        "site_types": ["theater", "art_space"],
        "year_opened": 1989,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Highways founded", "date": "1989", "description": "Co-founded by performance artist Tim Miller and director Linda Burnham as a space for marginalized voices during the AIDS crisis."},
        ],
        "related_figures": [
            {"name": "Tim Miller", "role": "Co-founder", "description": "Performance artist and one of the 'NEA Four' whose work was defunded by the National Endowment for the Arts."},
        ],
    },
    {
        "transaction_id": "7cY7zW5bJ9iD6fKeQ4vR0tMmP2hO8aGrL1dX9yIjE",
        "name": "West Hollywood Library",
        "location": {"type": "Point", "coordinates": [-118.3659, 34.0908]},
        "place_type": "current",
        "category": "library",
        "safety_score": 91,
        "upvote_count": 176,
        "description": "Award-winning public library in WeHo with extensive LGBTQ+ collection. Hosts queer book clubs, film screenings, and community programming.",
        "address": "625 N San Vicente Blvd, West Hollywood, CA 90069",
        "movements": ["pride"],
        "community_tags": ["gay", "lesbian", "queer", "youth"],
        "site_types": ["library"],
        "year_opened": 2011,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "8dZ8aX6cK0jE7gLfR5wS1uNnQ3iP9bHsM2eY0zJkF",
        "name": "Catch One",
        "location": {"type": "Point", "coordinates": [-118.3295, 34.053]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 87,
        "upvote_count": 203,
        "description": "Legendary nightclub formerly known as Jewel's Catch One \u2014 the first Black-owned disco in the US. A safe haven for LGBTQ+ people of color since 1973.",
        "address": "5006 W Pico Blvd, Los Angeles, CA 90019",
        "photos": ["https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800"],
        "movements": ["gay_liberation", "aids_activism", "pride", "ballroom_culture"],
        "community_tags": ["gay", "lesbian", "bipoc_queer", "trans", "drag"],
        "site_types": ["nightclub", "bar"],
        "year_opened": 1973,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Jewel's Catch One opens", "date": "1973", "description": "Jewel Thais-Williams opened the first Black-owned disco in the US, creating a safe haven for LGBTQ+ people of color."},
            {"title": "Reopens as Catch One", "date": "2018", "description": "After a brief closure, the venue reopened as Catch One, a live music and events venue honoring its LGBTQ+ legacy."},
        ],
        "related_figures": [
            {"name": "Jewel Thais-Williams", "role": "Founder", "description": "Pioneering Black lesbian entrepreneur who created the first Black-owned disco and an AIDS-era sanctuary."},
        ],
    },
    {
        "transaction_id": "9eA9bY7dL1kF8hMgS6xT2vOoR4jQ0cItN3fZ1aKlG",
        "name": "Stonewall National Monument (LA)",
        "location": {"type": "Point", "coordinates": [-118.3875, 34.083]},
        "place_type": "historical",
        "category": "park",
        "safety_score": 75,
        "upvote_count": 221,
        "description": "Memorial park in West Hollywood commemorating the Stonewall uprising and LGBTQ+ civil rights movement. Features rainbow pylons and historical plaques.",
        "era": "2010s",
        "address": "8840 Santa Monica Blvd, West Hollywood, CA 90069",
        "movements": ["stonewall", "gay_liberation", "pride"],
        "community_tags": ["gay", "lesbian", "trans", "queer"],
        "site_types": ["memorial", "park"],
        "year_opened": 2012,
        "still_exists": "yes",
        "significance": "regional",
    },
    # ── Additional LA Historical ──────────────────────────────────────────────
    {
        "transaction_id": "Af1Bx2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOm",
        "name": "Metropolitan Community Church",
        "location": {"type": "Point", "coordinates": [-118.2833, 34.1049]},
        "place_type": "historical",
        "category": "other",
        "safety_score": 80,
        "upvote_count": 195,
        "description": "The world's first LGBTQ+-affirming church, founded by Rev. Troy Perry in 1968 with 12 people in a living room. Now the mother church of a denomination with over 170 congregations in 37 countries.",
        "era": "1968-present",
        "address": "4607 Prospect Ave, Los Angeles, CA 90027",
        "movements": ["gay_liberation", "aids_activism", "marriage_equality"],
        "community_tags": ["gay", "lesbian", "trans", "queer"],
        "site_types": ["religious_space"],
        "year_opened": 1968,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "First worship service", "date": "1968-10-06", "description": "Rev. Troy Perry held the first service with 12 people in his living room in Huntington Park."},
            {"title": "MCC arson attack", "date": "1973-01-27", "description": "The MCC Mother Church was destroyed by arson, a devastating act of anti-LGBTQ+ violence."},
            {"title": "First same-sex church wedding", "date": "1969-03", "description": "Rev. Perry performed one of the first publicized same-sex weddings in the US."},
        ],
        "related_figures": [
            {"name": "Rev. Troy Perry", "role": "Founder", "description": "Founded the Metropolitan Community Church, the world's first LGBTQ+-affirming denomination."},
        ],
    },
    {
        "transaction_id": "Bg2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPl",
        "name": "Studio One",
        "location": {"type": "Point", "coordinates": [-118.3841, 34.0833]},
        "place_type": "historical",
        "category": "bar",
        "safety_score": 74,
        "upvote_count": 178,
        "description": "Legendary gay discotheque that operated from 1974 to 1993, explicitly conceived as a haven for gay men during the disco era. Became ground zero for AIDS activism and a cultural touchstone of queer LA nightlife.",
        "era": "1974-1993",
        "address": "661 N Robertson Blvd, West Hollywood, CA 90069",
        "movements": ["gay_liberation", "aids_activism", "pride"],
        "community_tags": ["gay"],
        "site_types": ["nightclub", "bar"],
        "year_opened": 1974,
        "year_closed": 1993,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "Studio One opens", "date": "1974", "description": "Opened by Scott Forbes as a high-end gay discotheque during the height of the disco era."},
            {"title": "AIDS benefit concerts begin", "date": "1982", "description": "Studio One became a key venue for AIDS fundraisers and awareness events as the epidemic devastated the community."},
        ],
    },
    {
        "transaction_id": "Ch3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQk",
        "name": "The Patch Bar",
        "location": {"type": "Point", "coordinates": [-118.264, 33.7915]},
        "place_type": "historical",
        "category": "bar",
        "safety_score": 62,
        "upvote_count": 96,
        "description": "Site of the 1968 'Flower Power' protest, one of the earliest gay liberation demonstrations in the US. When police raided the bar, owner Lee Glaze led patrons to the police station carrying bouquets of flowers in peaceful protest.",
        "era": "1968",
        "address": "Harbor Gateway, Wilmington, CA 90744",
        "movements": ["gay_liberation"],
        "community_tags": ["gay"],
        "site_types": ["bar", "protest_site"],
        "year_opened": 1966,
        "year_closed": 1969,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "'Flower Power' protest", "date": "1968-03-08", "description": "Owner Lee Glaze led patrons to the police station carrying flowers after a raid, in one of the first peaceful gay liberation demonstrations."},
        ],
        "related_figures": [
            {"name": "Lee Glaze", "role": "Owner/Activist", "description": "Bar owner who organized the pioneering 'Flower Power' protest against police raids."},
        ],
    },
    {
        "transaction_id": "Di4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRj",
        "name": "Barney's Beanery",
        "location": {"type": "Point", "coordinates": [-118.3736, 34.0907]},
        "place_type": "historical",
        "category": "other",
        "safety_score": 55,
        "upvote_count": 132,
        "description": "Site of a pivotal LGBTQ+ civil rights moment. The restaurant displayed a 'Fagots Stay Out' sign for decades until the Gay Liberation Front staged a protest on February 7, 1970. The sign was not permanently removed until 1985.",
        "era": "1930s-1985",
        "address": "8447 Santa Monica Blvd, West Hollywood, CA 90069",
        "movements": ["gay_liberation"],
        "community_tags": ["gay", "lesbian"],
        "site_types": ["protest_site"],
        "year_opened": 1920,
        "still_exists": "yes",
        "significance": "regional",
        "events": [
            {"title": "Gay Liberation Front protest", "date": "1970-02-07", "description": "Activists protested the 'Fagots Stay Out' sign that had been displayed for decades."},
            {"title": "Sign permanently removed", "date": "1985", "description": "The discriminatory sign was finally removed after years of protests and West Hollywood's cityhood."},
        ],
    },
    {
        "transaction_id": "Ej5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSi",
        "name": "Tom of Finland Foundation",
        "location": {"type": "Point", "coordinates": [-118.2594, 34.0746]},
        "place_type": "current",
        "category": "art_space",
        "safety_score": 79,
        "upvote_count": 115,
        "description": "Echo Park Craftsman house that was home to Finnish homoerotic artist Touko Laaksonen ('Tom of Finland'). Designated a Historic-Cultural Monument in 2016, it serves as a museum, archive, and safe space for erotic artists.",
        "address": "1421 Laveta Ter, Los Angeles, CA 90026",
        "movements": ["gay_liberation", "pride", "leather"],
        "community_tags": ["gay", "leather"],
        "site_types": ["art_space", "archive", "residence"],
        "year_opened": 1984,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "Historic-Cultural Monument designation", "date": "2016", "description": "The house was designated a Los Angeles Historic-Cultural Monument, recognizing its significance to LGBTQ+ art and culture."},
        ],
        "related_figures": [
            {"name": "Touko Laaksonen (Tom of Finland)", "role": "Artist/Resident", "description": "Finnish artist whose hyper-masculine homoerotic art became iconic in gay culture worldwide."},
            {"name": "Durk Dehner", "role": "Co-founder", "description": "Co-founded the Tom of Finland Foundation to preserve and promote erotic art."},
        ],
    },
    {
        "transaction_id": "Fk6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiTh",
        "name": "Triangle Square Senior Apartments",
        "location": {"type": "Point", "coordinates": [-118.3275, 34.0997]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 88,
        "upvote_count": 74,
        "description": "The nation's first LGBTQ+-affirming affordable housing development for seniors, located in Hollywood. This 104-unit complex provides supportive services, with units designated for seniors with HIV/AIDS.",
        "address": "1602 N Ivar Ave, Los Angeles, CA 90028",
        "movements": ["aids_activism"],
        "community_tags": ["gay", "lesbian", "elders"],
        "site_types": ["shelter", "community_center"],
        "year_opened": 2007,
        "still_exists": "yes",
        "significance": "national",
    },
    {
        "transaction_id": "Gl7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUg",
        "name": "AIDS Healthcare Foundation",
        "location": {"type": "Point", "coordinates": [-118.3257, 34.098]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 93,
        "upvote_count": 267,
        "description": "Global headquarters of the world's largest provider of HIV/AIDS treatment and prevention, co-founded by Michael Weinstein in 1987. Now serves over 2.5 million patients across 49 countries from its Hollywood base.",
        "address": "6255 W Sunset Blvd, Los Angeles, CA 90028",
        "movements": ["aids_activism"],
        "community_tags": ["gay", "queer", "bipoc_queer"],
        "site_types": ["health_clinic", "community_center"],
        "year_opened": 1987,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "AHF founded", "date": "1987", "description": "Founded during the height of the AIDS crisis to provide care and treatment to those affected."},
        ],
        "related_figures": [
            {"name": "Michael Weinstein", "role": "Co-founder/President", "description": "Co-founded AHF and built it into the world's largest AIDS service organization."},
        ],
    },
    {
        "transaction_id": "Hm8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUgVf",
        "name": "The Palms",
        "location": {"type": "Point", "coordinates": [-118.377, 34.0905]},
        "place_type": "historical",
        "category": "bar",
        "safety_score": 68,
        "upvote_count": 141,
        "description": "The oldest continuously running lesbian bar in Southern California and West Hollywood's last dedicated women's space. Hosted legends from Jim Morrison to Ellen DeGeneres before closing in 2013.",
        "era": "1965-2013",
        "address": "8572 Santa Monica Blvd, West Hollywood, CA 90069",
        "movements": ["gay_liberation", "pride"],
        "community_tags": ["lesbian", "bisexual"],
        "site_types": ["bar"],
        "year_opened": 1965,
        "year_closed": 2013,
        "still_exists": "no",
        "significance": "regional",
        "events": [
            {"title": "The Palms opens", "date": "1965", "description": "Opened as a neighborhood bar and became the longest-running lesbian bar in SoCal."},
            {"title": "Final closure", "date": "2013", "description": "Closed after nearly 50 years, marking the loss of WeHo's last dedicated women's bar."},
        ],
    },
    {
        "transaction_id": "In9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUgVfWe",
        "name": "The Woman's Building",
        "location": {"type": "Point", "coordinates": [-118.2372, 34.0694]},
        "place_type": "historical",
        "category": "art_space",
        "safety_score": 63,
        "upvote_count": 108,
        "description": "Home of the Feminist Studio Workshop (1975-1991), the first independent art school for women. A center for lesbian art and activism, hosting the first conference of lesbian artists in 1975 and the Great American Lesbian Art Show in 1980.",
        "era": "1973-1991",
        "address": "1727 N Spring St, Los Angeles, CA 90012",
        "movements": ["gay_liberation"],
        "community_tags": ["lesbian"],
        "site_types": ["art_space", "community_center"],
        "year_opened": 1973,
        "year_closed": 1991,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "Woman's Building opens", "date": "1973-11-28", "description": "Founded by Judy Chicago, Sheila de Bretteville, and Arlene Raven as a space for women's art and education."},
            {"title": "First Lesbian Art Conference", "date": "1975", "description": "Hosted the first conference of lesbian artists in the United States."},
            {"title": "Great American Lesbian Art Show", "date": "1980", "description": "Landmark exhibition celebrating lesbian artists and culture."},
        ],
        "related_figures": [
            {"name": "Judy Chicago", "role": "Co-founder", "description": "Pioneering feminist artist who co-founded the Woman's Building."},
            {"name": "Arlene Raven", "role": "Co-founder", "description": "Art historian and critic who championed feminist and lesbian art."},
        ],
    },
    {
        "transaction_id": "Jo0Kq1Lp2Mo3NnOmPlQkRjSiThUgVfWeXd",
        "name": "Jewel's Catch One (Original Site)",
        "location": {"type": "Point", "coordinates": [-118.327, 34.0477]},
        "place_type": "historical",
        "category": "bar",
        "safety_score": 76,
        "upvote_count": 189,
        "description": "Widely believed to be the first large-scale Black LGBTQ+ discotheque in the US, owned by Jewel Thais-Williams from 1973 to 2015. Called the 'Studio 54 of the West,' it hosted Sylvester, Whitney Houston, Madonna, and Luther Vandross.",
        "era": "1973-2015",
        "address": "4067 W Pico Blvd, Los Angeles, CA 90019",
        "movements": ["gay_liberation", "aids_activism", "pride", "ballroom_culture"],
        "community_tags": ["gay", "lesbian", "bipoc_queer", "trans", "drag"],
        "site_types": ["nightclub", "bar"],
        "year_opened": 1973,
        "year_closed": 2015,
        "still_exists": "partial",
        "significance": "national",
        "events": [
            {"title": "Catch One opens", "date": "1973", "description": "Jewel Thais-Williams opened the first Black-owned disco, creating a sanctuary for LGBTQ+ people of color."},
            {"title": "AIDS-era support services", "date": "1980s", "description": "Became a crucial community anchor during the AIDS crisis, hosting fundraisers and providing support."},
            {"title": "Catch One closes", "date": "2015", "description": "After 42 years, the original Catch One closed its doors."},
        ],
        "related_figures": [
            {"name": "Jewel Thais-Williams", "role": "Owner/Founder", "description": "Black lesbian entrepreneur who created and ran Catch One for over four decades."},
        ],
    },
]

# ── San Francisco ─────────────────────────────────────────────────────────────

SF_PLACES = [
    {
        "transaction_id": "SFa1Bx2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3Nn",
        "name": "Harvey Milk's Castro Camera",
        "location": {"type": "Point", "coordinates": [-122.4347, 37.7598]},
        "place_type": "historical",
        "category": "other",
        "safety_score": 90,
        "upvote_count": 345,
        "description": "Harvey Milk's camera shop and residence, which served as campaign headquarters and the epicenter of the Castro's growing gay community. Designated a San Francisco landmark and listed on the National Register of Historic Places.",
        "era": "1972-1978",
        "address": "575 Castro St, San Francisco, CA 94114",
        "movements": ["gay_liberation", "pride"],
        "community_tags": ["gay", "lesbian", "queer"],
        "site_types": ["residence", "memorial"],
        "year_opened": 1972,
        "year_closed": 1978,
        "still_exists": "partial",
        "significance": "international",
        "events": [
            {"title": "Harvey Milk opens Castro Camera", "date": "1972", "description": "Milk opened his camera shop, which became the de facto community center for the growing Castro gay neighborhood."},
            {"title": "Harvey Milk elected to SF Board of Supervisors", "date": "1977-11-08", "description": "Milk became the first openly gay person elected to public office in California, using the shop as campaign HQ."},
            {"title": "Harvey Milk assassinated", "date": "1978-11-27", "description": "Milk and Mayor George Moscone were assassinated at City Hall by former supervisor Dan White."},
            {"title": "National Register of Historic Places listing", "date": "2021", "description": "575 Castro Street was listed on the National Register for its association with Harvey Milk."},
        ],
        "related_figures": [
            {"name": "Harvey Milk", "role": "Owner/Politician", "description": "First openly gay elected official in California, assassinated in 1978. A pioneering figure in LGBTQ+ politics."},
            {"name": "Scott Smith", "role": "Partner/Campaign Manager", "description": "Harvey Milk's life partner who helped run the camera shop and political campaigns."},
        ],
    },
    {
        "transaction_id": "SFb2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOm",
        "name": "Twin Peaks Tavern",
        "location": {"type": "Point", "coordinates": [-122.435, 37.7618]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 89,
        "upvote_count": 201,
        "description": "The first gay bar in the US to feature uncovered plate-glass windows, allowing patrons to be seen from the street. Opened as a gay bar in 1972 by lesbian owners and designated a San Francisco historic landmark in 2013.",
        "address": "401 Castro St, San Francisco, CA 94114",
        "movements": ["gay_liberation", "pride"],
        "community_tags": ["gay", "lesbian"],
        "site_types": ["bar"],
        "year_opened": 1972,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Twin Peaks opens with uncovered windows", "date": "1972", "description": "Revolutionary act of visibility: the first gay bar to let patrons be seen from the street."},
            {"title": "San Francisco Historic Landmark designation", "date": "2013", "description": "Designated an SF landmark for its role in LGBTQ+ visibility."},
        ],
    },
    {
        "transaction_id": "SFc3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPl",
        "name": "GLBT Historical Society Museum",
        "location": {"type": "Point", "coordinates": [-122.4352, 37.7608]},
        "place_type": "current",
        "category": "other",
        "safety_score": 94,
        "upvote_count": 278,
        "description": "The first stand-alone museum of LGBTQ+ history and culture in the United States, featuring rotating exhibitions drawn from one of the world's largest LGBTQ+ archival collections, founded in 1985.",
        "address": "4127 18th St, San Francisco, CA 94114",
        "movements": ["gay_liberation", "aids_activism", "pride", "trans_rights"],
        "community_tags": ["gay", "lesbian", "bisexual", "trans", "queer"],
        "site_types": ["archive", "art_space"],
        "year_opened": 1985,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "GLBT Historical Society founded", "date": "1985", "description": "Established to collect, preserve, and interpret the history of LGBTQ+ people."},
            {"title": "Museum opens in the Castro", "date": "2011", "description": "The first full-scale LGBTQ+ history museum opened in the Castro neighborhood."},
        ],
    },
    {
        "transaction_id": "SFd4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQk",
        "name": "Compton's Cafeteria Riot Site",
        "location": {"type": "Point", "coordinates": [-122.4111, 37.7834]},
        "place_type": "historical",
        "category": "other",
        "safety_score": 72,
        "upvote_count": 256,
        "description": "Site of the 1966 Compton's Cafeteria riot, one of the first LGBTQ+ uprisings in US history, predating Stonewall by three years. A landmark moment in the transgender rights movement when trans women and drag queens fought back against police harassment.",
        "era": "1966",
        "address": "101 Taylor St, San Francisco, CA 94102",
        "movements": ["trans_rights", "gay_liberation"],
        "community_tags": ["trans", "drag", "bipoc_queer"],
        "site_types": ["cafe", "protest_site"],
        "year_opened": 1954,
        "year_closed": 1972,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "Compton's Cafeteria Riot", "date": "1966-08", "description": "Trans women and drag queens fought back when police attempted to arrest them, throwing dishes and smashing windows in one of the first trans uprisings."},
            {"title": "Historical plaque installed", "date": "2006", "description": "A bronze plaque was unveiled at the site, commemorating the 40th anniversary of the riot."},
        ],
        "related_figures": [
            {"name": "Felicia Flames Elizondo", "role": "Participant/Activist", "description": "Trans activist who participated in the riot and continued advocating for trans rights for decades."},
        ],
    },
    {
        "transaction_id": "SFe5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRj",
        "name": "National AIDS Memorial Grove",
        "location": {"type": "Point", "coordinates": [-122.4589, 37.7698]},
        "place_type": "current",
        "category": "park",
        "safety_score": 85,
        "upvote_count": 312,
        "description": "A dedicated living memorial in Golden Gate Park honoring those lost to AIDS. Permanent home of the AIDS Memorial Quilt, which contains over 50,000 panels with more than 110,000 names.",
        "address": "Nancy Pelosi Dr & Bowling Green Dr, Golden Gate Park, San Francisco, CA 94122",
        "movements": ["aids_activism"],
        "community_tags": ["gay", "queer", "bipoc_queer"],
        "site_types": ["memorial", "park"],
        "year_opened": 1991,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Grove established", "date": "1991", "description": "Created as a living memorial in Golden Gate Park to honor those lost to AIDS."},
            {"title": "Designated a National Memorial by Congress", "date": "1996", "description": "Congress designated it a National AIDS Memorial, the only federally designated AIDS memorial."},
            {"title": "AIDS Memorial Quilt finds permanent home", "date": "2020", "description": "The National AIDS Memorial became the permanent home of the AIDS Memorial Quilt."},
        ],
        "related_figures": [
            {"name": "Cleve Jones", "role": "Quilt Creator", "description": "Created the AIDS Memorial Quilt in 1985, which became the largest community art project in the world."},
        ],
    },
    {
        "transaction_id": "SFf6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSi",
        "name": "Harvey Milk Plaza",
        "location": {"type": "Point", "coordinates": [-122.435, 37.7625]},
        "place_type": "current",
        "category": "park",
        "safety_score": 91,
        "upvote_count": 367,
        "description": "Public plaza at the intersection of Castro and Market Streets honoring Harvey Milk, featuring the iconic giant rainbow flag visible throughout the neighborhood. A gathering point for community celebrations and memorials.",
        "address": "Castro St & Market St, San Francisco, CA 94114",
        "movements": ["gay_liberation", "pride"],
        "community_tags": ["gay", "lesbian", "queer", "trans"],
        "site_types": ["memorial", "park"],
        "year_opened": 1985,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "Plaza dedicated to Harvey Milk", "date": "1985", "description": "The plaza above Castro Muni station was officially named after Harvey Milk."},
            {"title": "Giant rainbow flag installed", "date": "1997", "description": "A large rainbow flag was permanently installed, becoming an iconic symbol of the Castro and LGBTQ+ pride."},
        ],
        "related_figures": [
            {"name": "Harvey Milk", "role": "Honoree", "description": "First openly gay elected official in California, the plaza bears his name."},
            {"name": "Gilbert Baker", "role": "Flag Creator", "description": "Designed the original rainbow flag in 1978, which flies permanently at the plaza."},
        ],
    },
    {
        "transaction_id": "SFg7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiTh",
        "name": "SF LGBT Center",
        "location": {"type": "Point", "coordinates": [-122.4238, 37.7718]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 95,
        "upvote_count": 289,
        "description": "San Francisco's only nonprofit serving all members of the LGBTQ+ community, offering critical safety net programs since 2002 from its iconic bright purple building at Market Street.",
        "address": "1800 Market St, San Francisco, CA 94102",
        "movements": ["pride", "trans_rights", "aids_activism"],
        "community_tags": ["gay", "lesbian", "bisexual", "trans", "queer", "nonbinary", "youth", "elders"],
        "site_types": ["community_center"],
        "year_opened": 2002,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "SFh8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUg",
        "name": "Aunt Charlie's Lounge",
        "location": {"type": "Point", "coordinates": [-122.412, 37.7831]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 81,
        "upvote_count": 134,
        "description": "One of the last remaining LGBTQ+ dive bars in the Tenderloin, famous for its Hot Boxxx Girls drag show. A beloved holdout of old-school queer nightlife in a rapidly gentrifying neighborhood.",
        "address": "133 Turk St, San Francisco, CA 94102",
        "movements": ["drag_culture", "pride"],
        "community_tags": ["gay", "drag", "queer"],
        "site_types": ["bar"],
        "year_opened": 1987,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "SFi9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUgVf",
        "name": "The Stud",
        "location": {"type": "Point", "coordinates": [-122.4134, 37.7718]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 84,
        "upvote_count": 167,
        "description": "San Francisco's oldest gay bar, operating in SoMa since 1966. Renowned for eclectic theme nights and as a cooperative owned by a collective of queer artists and performers.",
        "address": "1535 Folsom St, San Francisco, CA 94103",
        "movements": ["gay_liberation", "drag_culture", "pride"],
        "community_tags": ["gay", "queer", "nonbinary", "drag"],
        "site_types": ["bar", "nightclub"],
        "year_opened": 1966,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "The Stud opens", "date": "1966", "description": "Opened as one of the first gay bars in SoMa, becoming SF's longest-running gay bar."},
            {"title": "Becomes a worker cooperative", "date": "2016", "description": "Transitioned to cooperative ownership by a collective of queer artists and performers."},
        ],
    },
    {
        "transaction_id": "SFj0Kq1Lp2Mo3NnOmPlQkRjSiThUgVfWe",
        "name": "Lyon-Martin House",
        "location": {"type": "Point", "coordinates": [-122.4285, 37.7479]},
        "place_type": "historical",
        "category": "other",
        "safety_score": 77,
        "upvote_count": 198,
        "description": "Home of pioneers Phyllis Lyon and Del Martin, who founded the Daughters of Bilitis here in 1955 \u2014 the first lesbian civil rights organization in the US. Designated San Francisco's first landmark of lesbian activism in 2021.",
        "era": "1955-present",
        "address": "651 Duncan St, San Francisco, CA 94131",
        "movements": ["homophile_movement", "gay_liberation", "marriage_equality"],
        "community_tags": ["lesbian"],
        "site_types": ["residence", "memorial"],
        "year_opened": 1955,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Daughters of Bilitis founded", "date": "1955-09", "description": "Phyllis Lyon and Del Martin founded the first lesbian civil rights organization in the US at this house."},
            {"title": "Lyon and Martin marry", "date": "2008-06-16", "description": "The couple became the first same-sex couple to legally marry in San Francisco after the California Supreme Court ruling."},
            {"title": "SF Landmark designation", "date": "2021", "description": "Designated San Francisco's first landmark of lesbian activism."},
        ],
        "related_figures": [
            {"name": "Phyllis Lyon", "role": "Co-founder", "description": "Co-founded the Daughters of Bilitis and spent decades fighting for lesbian and women's rights."},
            {"name": "Del Martin", "role": "Co-founder", "description": "Pioneering lesbian activist who co-founded DOB and fought for LGBTQ+ and women's rights."},
        ],
    },
    {
        "transaction_id": "SFk1Lp2Mo3NnOmPlQkRjSiThUgVfWeXd",
        "name": "Tenderloin Museum",
        "location": {"type": "Point", "coordinates": [-122.4148, 37.7834]},
        "place_type": "current",
        "category": "other",
        "safety_score": 73,
        "upvote_count": 89,
        "description": "Neighborhood museum dedicated to preserving the Tenderloin's rich history, including its central role in LGBTQ+ activism and the 1966 Compton's Cafeteria Riot that helped launch the trans rights movement.",
        "address": "398 Eddy St, San Francisco, CA 94102",
        "movements": ["trans_rights", "gay_liberation"],
        "community_tags": ["trans", "queer", "bipoc_queer"],
        "site_types": ["archive"],
        "year_opened": 2015,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "SFl2Mo3NnOmPlQkRjSiThUgVfWeXdYc",
        "name": "Pink Triangle Park & Memorial",
        "location": {"type": "Point", "coordinates": [-122.4365, 37.7621]},
        "place_type": "current",
        "category": "park",
        "safety_score": 82,
        "upvote_count": 156,
        "description": "The first permanent freestanding memorial in the Americas to LGBTQ+ victims of the Holocaust. Its 15 stone pillars represent the estimated 15,000 gay men who perished in Nazi concentration camps.",
        "address": "Market St & 17th St, San Francisco, CA 94114",
        "movements": ["pride"],
        "community_tags": ["gay"],
        "site_types": ["memorial", "park"],
        "year_opened": 2003,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "Memorial dedicated", "date": "2003", "description": "The first permanent freestanding memorial to LGBTQ+ Holocaust victims in the Americas was dedicated in the Castro."},
        ],
    },
    {
        "transaction_id": "SFm3NnOmPlQkRjSiThUgVfWeXdYcZb",
        "name": "Rainbow Honor Walk",
        "location": {"type": "Point", "coordinates": [-122.435, 37.761]},
        "place_type": "current",
        "category": "other",
        "safety_score": 86,
        "upvote_count": 143,
        "description": "An LGBTQ+ Walk of Fame featuring bronze sidewalk plaques honoring notable queer historical figures. Installed in 2014 along Castro Street, it is the world's first rainbow honor walk.",
        "address": "Castro St (between Market & 19th), San Francisco, CA 94114",
        "movements": ["pride"],
        "community_tags": ["gay", "lesbian", "bisexual", "trans", "queer"],
        "site_types": ["memorial"],
        "year_opened": 2014,
        "still_exists": "yes",
        "significance": "national",
    },
    {
        "transaction_id": "SFn4OmPlQkRjSiThUgVfWeXdYcZbAa",
        "name": "LYRIC",
        "location": {"type": "Point", "coordinates": [-122.4264, 37.7631]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 90,
        "upvote_count": 98,
        "description": "Lavender Youth Recreation & Information Center, serving LGBTQQ+ youth through education, career training, health promotion, and leadership development. A vital resource for queer young people since 1988.",
        "address": "127 Collingwood St, San Francisco, CA 94114",
        "movements": ["pride", "trans_rights"],
        "community_tags": ["youth", "queer", "trans", "bipoc_queer"],
        "site_types": ["community_center"],
        "year_opened": 1988,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "SFo5PlQkRjSiThUgVfWeXdYcZbAaBx",
        "name": "The Lexington Club",
        "location": {"type": "Point", "coordinates": [-122.4214, 37.7598]},
        "place_type": "historical",
        "category": "bar",
        "safety_score": 66,
        "upvote_count": 121,
        "description": "San Francisco's last remaining lesbian bar, which operated in the Mission District from 1997 to 2015. A beloved dive bar and cultural hub for queer women that closed due to rising rents and gentrification.",
        "era": "1997-2015",
        "address": "3464 19th St, San Francisco, CA 94110",
        "movements": ["pride"],
        "community_tags": ["lesbian", "queer", "bisexual"],
        "site_types": ["bar"],
        "year_opened": 1997,
        "year_closed": 2015,
        "still_exists": "no",
        "significance": "regional",
        "events": [
            {"title": "The Lex opens", "date": "1997", "description": "Opened as a dedicated lesbian bar in the Mission, one of the last of its kind."},
            {"title": "Final closure", "date": "2015-04", "description": "Closed due to rising rents, becoming a symbol of LGBTQ+ displacement from gentrification."},
        ],
    },
]

# ── New York City ─────────────────────────────────────────────────────────────

NYC_PLACES = [
    {
        "transaction_id": "NYa1Bx2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3Nn",
        "name": "Stonewall Inn",
        "location": {"type": "Point", "coordinates": [-74.0021, 40.7338]},
        "place_type": "historical",
        "category": "bar",
        "safety_score": 96,
        "upvote_count": 523,
        "description": "Site of the 1969 Stonewall uprising that catalyzed the modern LGBTQ+ rights movement. The first US national monument dedicated to LGBTQ+ rights, designated by President Obama in 2016.",
        "era": "1969-present",
        "address": "51-53 Christopher St, New York, NY 10014",
        "movements": ["stonewall", "gay_liberation", "trans_rights", "pride"],
        "community_tags": ["trans", "gay", "lesbian", "drag", "bipoc_queer"],
        "site_types": ["bar", "protest_site", "memorial"],
        "year_opened": 1967,
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "Stonewall Riots begin", "date": "1969-06-28", "description": "Police raid sparked a multi-day uprising by LGBTQ+ patrons, catalyzing the modern gay rights movement."},
            {"title": "First Pride March", "date": "1970-06-28", "description": "The first Christopher Street Liberation Day March took place on the one-year anniversary of the riots."},
            {"title": "National Historic Landmark designation", "date": "2000-02-16", "description": "Designated a National Historic Landmark for its role in the LGBTQ+ civil rights movement."},
            {"title": "Stonewall National Monument created", "date": "2016-06-24", "description": "President Obama designated the Stonewall National Monument, the first US national monument to LGBTQ+ rights."},
        ],
        "related_figures": [
            {"name": "Marsha P. Johnson", "role": "Activist", "description": "Key figure in the Stonewall uprising, Black trans woman who became a leading voice for trans rights."},
            {"name": "Sylvia Rivera", "role": "Activist", "description": "Co-founded STAR (Street Transvestite Action Revolutionaries) with Marsha P. Johnson after Stonewall."},
            {"name": "Stormé DeLarverie", "role": "Activist", "description": "Biracial butch lesbian whose resistance at Stonewall is considered a catalyst for the uprising."},
        ],
    },
    {
        "transaction_id": "NYb2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOm",
        "name": "Christopher Park / Gay Liberation Monument",
        "location": {"type": "Point", "coordinates": [-74.0023, 40.7339]},
        "place_type": "current",
        "category": "park",
        "safety_score": 88,
        "upvote_count": 298,
        "description": "Small park directly across from the Stonewall Inn, featuring George Segal's 1992 'Gay Liberation' bronze sculptures depicting two same-sex couples. Part of the Stonewall National Monument.",
        "address": "Christopher St & Grove St, New York, NY 10014",
        "movements": ["stonewall", "gay_liberation", "pride"],
        "community_tags": ["gay", "lesbian", "queer"],
        "site_types": ["memorial", "park"],
        "still_exists": "yes",
        "significance": "international",
        "events": [
            {"title": "'Gay Liberation' sculptures installed", "date": "1992", "description": "George Segal's bronze sculptures depicting two same-sex couples were installed in the park."},
        ],
        "related_figures": [
            {"name": "George Segal", "role": "Artist", "description": "Created the 'Gay Liberation' sculptures, one of the first public artworks depicting same-sex couples."},
        ],
    },
    {
        "transaction_id": "NYc3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPl",
        "name": "Julius' Bar",
        "location": {"type": "Point", "coordinates": [-74.0017, 40.7339]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 87,
        "upvote_count": 234,
        "description": "Often called NYC's oldest continuously operating gay bar. Site of the famous 1966 'Sip-In' protest, where activists challenged the liquor authority's ban on serving gay patrons.",
        "address": "159 W 10th St, New York, NY 10014",
        "movements": ["homophile_movement", "gay_liberation"],
        "community_tags": ["gay"],
        "site_types": ["bar", "protest_site"],
        "year_opened": 1864,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "'Sip-In' protest", "date": "1966-04-21", "description": "Members of the Mattachine Society deliberately sought service to challenge the policy of refusing to serve gay patrons."},
        ],
        "related_figures": [
            {"name": "Dick Leitsch", "role": "Organizer", "description": "Mattachine Society leader who organized the 'Sip-In' protest at Julius'."},
        ],
    },
    {
        "transaction_id": "NYd4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQk",
        "name": "NYC AIDS Memorial",
        "location": {"type": "Point", "coordinates": [-74.0012, 40.7372]},
        "place_type": "current",
        "category": "park",
        "safety_score": 83,
        "upvote_count": 267,
        "description": "Memorial at St. Vincent's Triangle honoring the 100,000+ New Yorkers lost to AIDS. Located adjacent to the former St. Vincent's Hospital, which housed the city's first and largest AIDS ward.",
        "address": "76 Greenwich Ave, New York, NY 10011",
        "movements": ["aids_activism"],
        "community_tags": ["gay", "queer", "bipoc_queer"],
        "site_types": ["memorial", "park"],
        "year_opened": 2016,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Memorial dedicated", "date": "2016-12-01", "description": "Opened on World AIDS Day, honoring the 100,000+ New Yorkers lost to AIDS."},
        ],
    },
    {
        "transaction_id": "NYe5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRj",
        "name": "The Center (NYC LGBT Community Center)",
        "location": {"type": "Point", "coordinates": [-74.0003, 40.7381]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 96,
        "upvote_count": 412,
        "description": "The nexus of LGBTQ+ culture in NYC since 1983, offering extensive programming, a library of LGBTQ+ literature, the National History Archive, art exhibitions, and social services from a landmarked building.",
        "address": "208 W 13th St, New York, NY 10011",
        "movements": ["gay_liberation", "aids_activism", "trans_rights", "pride", "marriage_equality"],
        "community_tags": ["gay", "lesbian", "bisexual", "trans", "queer", "nonbinary", "youth", "elders"],
        "site_types": ["community_center", "archive", "art_space"],
        "year_opened": 1983,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "The Center opens", "date": "1983", "description": "Founded to serve as a home for NYC's LGBTQ+ community during the height of the AIDS crisis."},
            {"title": "ACT UP holds first meeting", "date": "1987-03-10", "description": "The AIDS Coalition to Unleash Power held its first meeting at The Center, launching one of the most effective activist organizations in history."},
        ],
        "related_figures": [
            {"name": "Larry Kramer", "role": "ACT UP Co-founder", "description": "Writer and activist who co-founded ACT UP at The Center, transforming AIDS activism."},
        ],
    },
    {
        "transaction_id": "NYf6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSi",
        "name": "Gay Activists Alliance Firehouse",
        "location": {"type": "Point", "coordinates": [-74.0008, 40.7241]},
        "place_type": "historical",
        "category": "community_center",
        "safety_score": 70,
        "upvote_count": 145,
        "description": "Former firehouse that served as headquarters for the Gay Activists Alliance from 1971-1974. Called NYC's 'first gay community center,' it hosted weekly Saturday dances with crowds of up to 1,500 people.",
        "era": "1971-1974",
        "address": "99 Wooster St, New York, NY 10012",
        "movements": ["gay_liberation"],
        "community_tags": ["gay", "lesbian"],
        "site_types": ["community_center"],
        "year_opened": 1971,
        "year_closed": 1974,
        "still_exists": "partial",
        "significance": "national",
        "events": [
            {"title": "GAA occupies the firehouse", "date": "1971", "description": "The Gay Activists Alliance set up headquarters in the abandoned firehouse, creating NYC's first gay community center."},
            {"title": "Firehouse arson", "date": "1974-10-15", "description": "The firehouse was destroyed by arson, ending GAA's tenure but not the movement."},
        ],
    },
    {
        "transaction_id": "NYg7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiTh",
        "name": "Caffe Cino",
        "location": {"type": "Point", "coordinates": [-74.0035, 40.7318]},
        "place_type": "historical",
        "category": "cafe",
        "safety_score": 67,
        "upvote_count": 134,
        "description": "Birthplace of Off-Off-Broadway theater (1958-1968), opened by gay Italian-American Joe Cino. Pioneered experimental and gay theater at a time when portraying homosexuality on stage was groundbreaking.",
        "era": "1958-1968",
        "address": "31 Cornelia St, New York, NY 10014",
        "movements": ["gay_liberation"],
        "community_tags": ["gay", "queer"],
        "site_types": ["cafe", "theater"],
        "year_opened": 1958,
        "year_closed": 1968,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "Caffe Cino opens", "date": "1958-12", "description": "Joe Cino opened his coffeehouse, launching what would become Off-Off-Broadway theater."},
            {"title": "First openly gay plays staged", "date": "1960s", "description": "Premiered works by gay playwrights at a time when homosexuality was taboo on stage."},
        ],
        "related_figures": [
            {"name": "Joe Cino", "role": "Founder", "description": "Gay Italian-American who created Off-Off-Broadway theater and fostered queer artistic expression."},
        ],
    },
    {
        "transaction_id": "NYh8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUg",
        "name": "Lesbian Herstory Archives",
        "location": {"type": "Point", "coordinates": [-73.9806, 40.6623]},
        "place_type": "current",
        "category": "library",
        "safety_score": 92,
        "upvote_count": 198,
        "description": "The nation's oldest and largest collection of lesbian-related historical material, founded in 1974. Brooklyn's first individually landmarked LGBTQ+ site, housed in a Park Slope brownstone since 1993.",
        "address": "484 14th St, Brooklyn, NY 11215",
        "movements": ["gay_liberation", "pride"],
        "community_tags": ["lesbian"],
        "site_types": ["archive", "library"],
        "year_opened": 1974,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Archives founded", "date": "1974", "description": "Joan Nestle and Deborah Edel founded the archives in their apartment to preserve lesbian history."},
            {"title": "Moved to Park Slope brownstone", "date": "1993", "description": "The collection moved to a dedicated brownstone in Park Slope, purchased by the community."},
        ],
        "related_figures": [
            {"name": "Joan Nestle", "role": "Co-founder", "description": "Writer and activist who co-founded the archives to ensure lesbian history was preserved by the community."},
        ],
    },
    {
        "transaction_id": "NYi9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUgVf",
        "name": "Pier 45 / Christopher Street Pier",
        "location": {"type": "Point", "coordinates": [-74.0111, 40.7353]},
        "place_type": "current",
        "category": "park",
        "safety_score": 79,
        "upvote_count": 213,
        "description": "For over a century, a vital gathering place for the LGBTQ+ community, evolving from a 1970s cruising destination to a safe haven for queer homeless youth of color. Connected to the legacy of Marsha P. Johnson and Sylvia Rivera.",
        "address": "West St & Christopher St, Hudson River Park, New York, NY 10014",
        "movements": ["stonewall", "trans_rights", "ballroom_culture"],
        "community_tags": ["trans", "bipoc_queer", "youth", "gay", "drag"],
        "site_types": ["park"],
        "still_exists": "yes",
        "significance": "national",
        "related_figures": [
            {"name": "Marsha P. Johnson", "role": "Community Figure", "description": "Trans activist whose body was found in the Hudson River near the pier in 1992, galvanizing the trans rights movement."},
            {"name": "Sylvia Rivera", "role": "Activist", "description": "Co-founded STAR and advocated for homeless queer youth who gathered at the piers."},
        ],
    },
    {
        "transaction_id": "NYj0Kq1Lp2Mo3NnOmPlQkRjSiThUgVfWe",
        "name": "Oscar Wilde Bookshop",
        "location": {"type": "Point", "coordinates": [-74.0003, 40.7334]},
        "place_type": "historical",
        "category": "bookstore",
        "safety_score": 71,
        "upvote_count": 167,
        "description": "The nation's first gay and lesbian bookstore, opened by Craig Rodwell in 1967. The first gay pride parade in 1970 was planned within its walls. Operated until 2009.",
        "era": "1967-2009",
        "address": "15 Christopher St, New York, NY 10014",
        "movements": ["gay_liberation", "pride", "homophile_movement"],
        "community_tags": ["gay", "lesbian"],
        "site_types": ["bookstore"],
        "year_opened": 1967,
        "year_closed": 2009,
        "still_exists": "no",
        "significance": "national",
        "events": [
            {"title": "Bookshop opens", "date": "1967-11-24", "description": "Craig Rodwell opened the first gay and lesbian bookstore in the US on Mercer Street."},
            {"title": "First Pride March planned", "date": "1970", "description": "The first Christopher Street Liberation Day March (now Pride) was planned within the bookshop."},
            {"title": "Final closure", "date": "2009-03-29", "description": "The bookshop closed after 42 years, victim of changing retail and economic pressures."},
        ],
        "related_figures": [
            {"name": "Craig Rodwell", "role": "Founder", "description": "Opened the first gay bookstore in the US and organized the first Pride march."},
        ],
    },
    {
        "transaction_id": "NYk1Lp2Mo3NnOmPlQkRjSiThUgVfWeXd",
        "name": "Henrietta Hudson",
        "location": {"type": "Point", "coordinates": [-74.0067, 40.7308]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 86,
        "upvote_count": 178,
        "description": "New York City's longest-operating lesbian bar, located in the West Village. A historic queer women's space that has served as a cornerstone of the lesbian community for decades.",
        "address": "438-444 Hudson St, New York, NY 10014",
        "movements": ["pride"],
        "community_tags": ["lesbian", "bisexual", "queer"],
        "site_types": ["bar"],
        "year_opened": 1991,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "NYl2Mo3NnOmPlQkRjSiThUgVfWeXdYc",
        "name": "Marie's Crisis Cafe",
        "location": {"type": "Point", "coordinates": [-74.0028, 40.7325]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 84,
        "upvote_count": 189,
        "description": "Legendary West Village piano bar and gay bar where patrons gather nightly for singalongs of Broadway show tunes. A beloved institution of queer nightlife culture since 1929.",
        "address": "59 Grove St, New York, NY 10014",
        "movements": ["pride", "drag_culture"],
        "community_tags": ["gay", "queer"],
        "site_types": ["bar"],
        "year_opened": 1929,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "NYm3NnOmPlQkRjSiThUgVfWeXdYcZb",
        "name": "Cubbyhole",
        "location": {"type": "Point", "coordinates": [-74.0031, 40.7367]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 88,
        "upvote_count": 156,
        "description": "One of only three remaining lesbian bars in NYC, this cozy Greenwich Village spot has been an inclusive 'neighborhood fusion bar' since 1994. Known for its eclectic ceiling decor and welcoming vibe.",
        "address": "281 W 12th St, New York, NY 10014",
        "movements": ["pride"],
        "community_tags": ["lesbian", "bisexual", "queer"],
        "site_types": ["bar"],
        "year_opened": 1994,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "NYn4OmPlQkRjSiThUgVfWeXdYcZbAa",
        "name": "Ali Forney Center",
        "location": {"type": "Point", "coordinates": [-73.9544, 40.8103]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 94,
        "upvote_count": 287,
        "description": "The largest organization in the US helping LGBTQ+ homeless youth, providing 162 beds nightly across 15 sites. Named after Ali Forney, a gender non-conforming youth murdered in 1997.",
        "address": "321 W 125th St, New York, NY 10027",
        "movements": ["trans_rights", "pride"],
        "community_tags": ["trans", "youth", "bipoc_queer", "queer"],
        "site_types": ["shelter", "community_center"],
        "year_opened": 2002,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "Ali Forney Center founded", "date": "2002", "description": "Carl Siciliano founded the center after the murder of Ali Forney, a gender non-conforming homeless youth."},
        ],
        "related_figures": [
            {"name": "Ali Forney", "role": "Namesake", "description": "Gender non-conforming youth whose murder in 1997 inspired the founding of the center."},
            {"name": "Carl Siciliano", "role": "Founder", "description": "Founded the center after working with homeless LGBTQ+ youth for years."},
        ],
    },
    {
        "transaction_id": "NYo5PlQkRjSiThUgVfWeXdYcZbAaBx",
        "name": "Bayard Rustin Residence",
        "location": {"type": "Point", "coordinates": [-73.9968, 40.7484]},
        "place_type": "historical",
        "category": "other",
        "safety_score": 69,
        "upvote_count": 123,
        "description": "Home of Bayard Rustin, the openly gay civil rights leader who was the chief organizer of the 1963 March on Washington. Listed on the National Register of Historic Places in 2016 for its LGBTQ+ significance.",
        "era": "1962-1987",
        "address": "340 W 28th St, New York, NY 10001",
        "movements": ["gay_liberation"],
        "community_tags": ["gay", "bipoc_queer"],
        "site_types": ["residence", "memorial"],
        "year_opened": 1962,
        "year_closed": 1987,
        "still_exists": "yes",
        "significance": "national",
        "events": [
            {"title": "National Register of Historic Places listing", "date": "2016", "description": "Listed on the NRHP for its significance to LGBTQ+ history as the home of Bayard Rustin."},
            {"title": "Posthumous Presidential Medal of Freedom", "date": "2013-08-08", "description": "President Obama posthumously awarded Rustin the Presidential Medal of Freedom."},
        ],
        "related_figures": [
            {"name": "Bayard Rustin", "role": "Resident/Activist", "description": "Openly gay civil rights leader who organized the 1963 March on Washington and mentored Dr. Martin Luther King Jr."},
        ],
    },
    {
        "transaction_id": "NYp6QkRjSiThUgVfWeXdYcZbAaBxCy",
        "name": "Audre Lorde Project",
        "location": {"type": "Point", "coordinates": [-73.9723, 40.6862]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 91,
        "upvote_count": 176,
        "description": "A community organizing center for LGBTQ+ people of color in Fort Greene, Brooklyn, founded in 1994. Named after writer and activist Audre Lorde, it prioritizes the needs of queer communities historically left out of mainstream organizations.",
        "address": "85 S Oxford St, Brooklyn, NY 11217",
        "movements": ["trans_rights", "pride"],
        "community_tags": ["bipoc_queer", "trans", "queer", "two_spirit", "nonbinary"],
        "site_types": ["community_center"],
        "year_opened": 1994,
        "still_exists": "yes",
        "significance": "national",
        "related_figures": [
            {"name": "Audre Lorde", "role": "Namesake", "description": "Self-described 'Black, lesbian, mother, warrior, poet' whose intersectional activism inspired the organization."},
        ],
    },
]

# ── Miami ─────────────────────────────────────────────────────────────────────

MIAMI_PLACES = [
    {
        "transaction_id": "MIa1Bx2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3Nn",
        "name": "Palace Bar",
        "location": {"type": "Point", "coordinates": [-80.1303, 25.7808]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 91,
        "upvote_count": 267,
        "description": "Iconic oceanfront LGBTQ+ institution since 1988, famous for its legendary drag brunches every Friday through Sunday. Located directly across from Miami's gay beach at 12th Street, a symbol of South Beach queer culture.",
        "address": "1052 Ocean Dr, Miami Beach, FL 33139",
        "movements": ["pride", "drag_culture"],
        "community_tags": ["gay", "drag", "queer"],
        "site_types": ["bar"],
        "year_opened": 1988,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "MIb2Cy3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOm",
        "name": "Twist",
        "location": {"type": "Point", "coordinates": [-80.1345, 25.7809]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 87,
        "upvote_count": 198,
        "description": "South Beach's largest and longest-running gay club, featuring seven different bars and multiple music styles across its sprawling venue. Known for its Latin-infused nights and diverse crowd.",
        "address": "1057 Washington Ave, Miami Beach, FL 33139",
        "movements": ["pride"],
        "community_tags": ["gay", "queer", "bipoc_queer"],
        "site_types": ["bar", "nightclub"],
        "year_opened": 1993,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "MIc3Dz4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPl",
        "name": "12th Street Beach (Gay Beach)",
        "location": {"type": "Point", "coordinates": [-80.1286, 25.7807]},
        "place_type": "current",
        "category": "park",
        "safety_score": 85,
        "upvote_count": 234,
        "description": "Miami's most famous LGBTQ+ beach, marked by rainbow flags and a rainbow-colored lifeguard station. The epicenter of the South Beach gay community and a focal point during Miami Pride celebrations.",
        "address": "Ocean Dr & 12th St, Miami Beach, FL 33139",
        "movements": ["pride"],
        "community_tags": ["gay", "lesbian", "queer", "trans"],
        "site_types": ["park"],
        "still_exists": "yes",
        "significance": "regional",
        "events": [
            {"title": "Rainbow lifeguard stand installed", "date": "2014", "description": "A rainbow-colored lifeguard stand was installed, making the beach an iconic symbol of LGBTQ+ Miami."},
        ],
    },
    {
        "transaction_id": "MId4Ew5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQk",
        "name": "R House Wynwood",
        "location": {"type": "Point", "coordinates": [-80.199, 25.8023]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 89,
        "upvote_count": 176,
        "description": "Award-winning LGBTQ+ restaurant and art gallery in the Wynwood Arts District, celebrated for its spectacular weekend drag brunches featuring top local performers.",
        "address": "2727 NW 2nd Ave, Miami, FL 33127",
        "movements": ["pride", "drag_culture"],
        "community_tags": ["gay", "drag", "queer", "bipoc_queer"],
        "site_types": ["bar", "art_space"],
        "year_opened": 2013,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "MIe5Fv6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRj",
        "name": "Azucar Nightclub",
        "location": {"type": "Point", "coordinates": [-80.2377, 25.7451]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 83,
        "upvote_count": 134,
        "description": "Popular Latin LGBTQ+ nightclub featuring drag wars shows, cabaret nights, go-go dancers, and DJs. A vibrant hub for Miami's Latin queer community.",
        "address": "2301 SW 32nd Ave, Miami, FL 33145",
        "movements": ["pride", "drag_culture"],
        "community_tags": ["gay", "drag", "bipoc_queer"],
        "site_types": ["nightclub", "bar"],
        "year_opened": 2007,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "MIf6Gu7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSi",
        "name": "LGBT Visitor Center",
        "location": {"type": "Point", "coordinates": [-80.1349, 25.774]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 90,
        "upvote_count": 98,
        "description": "Miami Beach's LGBTQ+ visitor center offering tourist information, free HIV/STI testing, support groups, and community engagement programs at the epicenter of South Beach.",
        "address": "1130 Washington Ave, Miami Beach, FL 33139",
        "movements": ["pride", "aids_activism"],
        "community_tags": ["gay", "lesbian", "queer", "trans"],
        "site_types": ["community_center", "health_clinic"],
        "year_opened": 2014,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "MIg7Ht8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiTh",
        "name": "Pridelines",
        "location": {"type": "Point", "coordinates": [-80.2073, 25.819]},
        "place_type": "current",
        "category": "community_center",
        "safety_score": 92,
        "upvote_count": 145,
        "description": "Miami-Dade County's only LGBTQ+ community center, located in Liberty City. Provides housing, mental health counseling, a clinic with PrEP/PEP, a food pantry, and comprehensive services for the community.",
        "address": "5775 NW 7th Ave, Miami, FL 33127",
        "movements": ["pride", "aids_activism", "trans_rights"],
        "community_tags": ["gay", "lesbian", "bisexual", "trans", "queer", "bipoc_queer", "youth"],
        "site_types": ["community_center", "health_clinic", "shelter"],
        "year_opened": 2009,
        "still_exists": "yes",
        "significance": "regional",
    },
    {
        "transaction_id": "MIh8Is9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUg",
        "name": "Gramps",
        "location": {"type": "Point", "coordinates": [-80.1948, 25.797]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 84,
        "upvote_count": 112,
        "description": "One of Miami's most LGBTQ-friendly bars, located in Wynwood. Hosts the popular Double Stubble queer party with DJs and rotating drag performers, alongside a sprawling indoor-outdoor space.",
        "address": "176 NW 24th St, Miami, FL 33127",
        "movements": ["pride", "drag_culture"],
        "community_tags": ["queer", "gay", "drag"],
        "site_types": ["bar"],
        "year_opened": 2013,
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "MIi9Jr0Kq1Lp2Mo3NnOmPlQkRjSiThUgVf",
        "name": "Haulover Beach",
        "location": {"type": "Point", "coordinates": [-80.1199, 25.9035]},
        "place_type": "current",
        "category": "park",
        "safety_score": 78,
        "upvote_count": 167,
        "description": "The largest sanctioned nude beach in the US, with a designated LGBTQ+ section. Located north of South Beach, this popular clothing-optional beach draws both locals and tourists to its white-sand expanse.",
        "address": "10800 Collins Ave, Miami Beach, FL 33154",
        "movements": ["pride"],
        "community_tags": ["gay", "queer"],
        "site_types": ["park"],
        "still_exists": "yes",
        "significance": "local",
    },
    {
        "transaction_id": "MIj0Kq1Lp2Mo3NnOmPlQkRjSiThUgVfWe",
        "name": "Kill Your Idol",
        "location": {"type": "Point", "coordinates": [-80.1311, 25.7868]},
        "place_type": "current",
        "category": "bar",
        "safety_score": 80,
        "upvote_count": 89,
        "description": "Eclectic South Beach dive bar hosting weekly drag shows, RuPaul's Drag Race watch parties, karaoke nights, and live music in an alternative, LGBTQ-friendly atmosphere.",
        "address": "222 Espanola Way, Miami Beach, FL 33139",
        "movements": ["pride", "drag_culture"],
        "community_tags": ["queer", "gay", "drag"],
        "site_types": ["bar"],
        "year_opened": 2011,
        "still_exists": "yes",
        "significance": "local",
    },
]

# ── Combined ──────────────────────────────────────────────────────────────────

PLACES = LA_PLACES + SF_PLACES + NYC_PLACES + MIAMI_PLACES


def seed():
    from models import Place, GeoJSONPoint, HistoricalEvent, RelatedFigure

    inserted = 0
    skipped = 0

    for p in PLACES:
        if Place.objects(transaction_id=p["transaction_id"]).first():
            skipped += 1
            continue

        events = [
            HistoricalEvent(**e) for e in p.get("events", [])
        ]
        figures = [
            RelatedFigure(**f) for f in p.get("related_figures", [])
        ]

        place = Place(
            name=p["name"],
            location=GeoJSONPoint(
                type=p["location"]["type"],
                coordinates=p["location"]["coordinates"],
            ),
            place_type=p["place_type"],
            category=p["category"],
            safety_score=p.get("safety_score", 0),
            upvote_count=p.get("upvote_count", 0),
            transaction_id=p["transaction_id"],
            status="approved",
            description=p.get("description"),
            era=p.get("era"),
            photos=p.get("photos"),
            address=p.get("address"),
            events=events,
            related_figures=figures,
            movements=p.get("movements", []),
            community_tags=p.get("community_tags", []),
            site_types=p.get("site_types", []),
            year_opened=p.get("year_opened"),
            year_closed=p.get("year_closed"),
            still_exists=p.get("still_exists"),
            significance=p.get("significance"),
            created_at=datetime.now(timezone.utc),
            indexed_at=datetime.now(timezone.utc),
        )
        place.save()
        inserted += 1

    print(f"Seed complete: {inserted} inserted, {skipped} skipped (already existed)")


def main():
    max_retries = 10
    for attempt in range(max_retries):
        try:
            connect(db=MONGO_DB, host=MONGO_URI, uuidRepresentation="standard")
            print(f"Connected to MongoDB ({MONGO_URI})")
            break
        except Exception as e:
            if attempt < max_retries - 1:
                print(f"MongoDB not ready (attempt {attempt + 1}/{max_retries}): {e}")
                time.sleep(3)
            else:
                raise RuntimeError(f"Could not connect to MongoDB after {max_retries} attempts") from e

    seed()


if __name__ == "__main__":
    main()
